// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tero/policy/v1/extension.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExtensionMode selects which slice of the telemetry stream the engine delivers
// to an extension, relative to its policy. {KEPT, DROPPED, UNMATCHED} are
// disjoint and partition the stream; MATCHED and ALL are convenience unions.
type ExtensionMode int32

const (
	ExtensionMode_EXTENSION_MODE_UNSPECIFIED ExtensionMode = 0 // treated as MATCHED
	// Matched the policy and survived the keep stage.
	ExtensionMode_EXTENSION_MODE_KEPT ExtensionMode = 1
	// Matched the policy but was removed by the keep stage (dropped, sampled out,
	// or rate limited). Its keep verdict is the record's final pipeline outcome,
	// which another matching policy may have caused. This is the "dump waste" mode.
	ExtensionMode_EXTENSION_MODE_DROPPED ExtensionMode = 2
	// Did not match the policy's matchers.
	ExtensionMode_EXTENSION_MODE_UNMATCHED ExtensionMode = 3
	// Matched the policy, regardless of keep outcome (KEPT + DROPPED). Default.
	ExtensionMode_EXTENSION_MODE_MATCHED ExtensionMode = 4
	// Every record of the signal type, regardless of match or keep
	// (KEPT + DROPPED + UNMATCHED).
	ExtensionMode_EXTENSION_MODE_ALL ExtensionMode = 5
)

// Enum value maps for ExtensionMode.
var (
	ExtensionMode_name = map[int32]string{
		0: "EXTENSION_MODE_UNSPECIFIED",
		1: "EXTENSION_MODE_KEPT",
		2: "EXTENSION_MODE_DROPPED",
		3: "EXTENSION_MODE_UNMATCHED",
		4: "EXTENSION_MODE_MATCHED",
		5: "EXTENSION_MODE_ALL",
	}
	ExtensionMode_value = map[string]int32{
		"EXTENSION_MODE_UNSPECIFIED": 0,
		"EXTENSION_MODE_KEPT":        1,
		"EXTENSION_MODE_DROPPED":     2,
		"EXTENSION_MODE_UNMATCHED":   3,
		"EXTENSION_MODE_MATCHED":     4,
		"EXTENSION_MODE_ALL":         5,
	}
)

func (x ExtensionMode) Enum() *ExtensionMode {
	p := new(ExtensionMode)
	*p = x
	return p
}

func (x ExtensionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tero_policy_v1_extension_proto_enumTypes[0].Descriptor()
}

func (ExtensionMode) Type() protoreflect.EnumType {
	return &file_tero_policy_v1_extension_proto_enumTypes[0]
}

func (x ExtensionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionMode.Descriptor instead.
func (ExtensionMode) EnumDescriptor() ([]byte, []int) {
	return file_tero_policy_v1_extension_proto_rawDescGZIP(), []int{0}
}

// Extension attaches implementation-specific behavior to a policy.
//
// Implementations MUST declare which extension types they support. An extension
// with an unrecognized type is handled per the spec (fail-open, or reject policy
// load when the extension is required for the policy's behavior).
type Extension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type identifier using reverse-FQDN notation (e.g. "com.usetero/s3-dump").
	// Implementations use this to route to the correct handler.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Version of the extension schema (semver, e.g. "1.0.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Opaque, type-defined configuration payload, deserialized by the handler
	// registered for `type`. The policy engine does not interpret it.
	Config []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// Which slice of traffic the engine delivers to this extension. Defaults to
	// MATCHED.
	Mode          ExtensionMode `protobuf:"varint,4,opt,name=mode,proto3,enum=tero.policy.v1.ExtensionMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_tero_policy_v1_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_extension_proto_rawDescGZIP(), []int{0}
}

func (x *Extension) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Extension) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Extension) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Extension) GetMode() ExtensionMode {
	if x != nil {
		return x.Mode
	}
	return ExtensionMode_EXTENSION_MODE_UNSPECIFIED
}

// ExtensionCapability declares a client's support for one extension type. The
// repeated `config` entries are opaque, type-defined capability descriptors —
// for example, the destinations the client can route to. The policy engine does
// not interpret them; the extension handler does. Providers use this to avoid
// sending policies whose extensions the client cannot satisfy.
type ExtensionCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension type identifier (e.g. "com.usetero/s3-dump").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Minimum supported extension version (semver, inclusive).
	MinVersion string `protobuf:"bytes,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	// Opaque, type-defined capability descriptors. For tero's s3-dump these are
	// serialized ExtensionTargetRefs (see tero_extensions.proto).
	Config        [][]byte `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionCapability) Reset() {
	*x = ExtensionCapability{}
	mi := &file_tero_policy_v1_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCapability) ProtoMessage() {}

func (x *ExtensionCapability) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionCapability.ProtoReflect.Descriptor instead.
func (*ExtensionCapability) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_extension_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionCapability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExtensionCapability) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *ExtensionCapability) GetConfig() [][]byte {
	if x != nil {
		return x.Config
	}
	return nil
}

// ExtensionConfig broadcasts opaque, type-defined configuration for one
// extension type to clients (via SyncResponse.extension_configs). Each `config`
// entry is parsed by the handler registered for `type`. For tero's s3-dump
// these are serialized ExtensionTargets (see tero_extensions.proto).
type ExtensionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension type identifier (e.g. "com.usetero/s3-dump").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Opaque, type-defined configuration payloads.
	Config        [][]byte `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionConfig) Reset() {
	*x = ExtensionConfig{}
	mi := &file_tero_policy_v1_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionConfig) ProtoMessage() {}

func (x *ExtensionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionConfig.ProtoReflect.Descriptor instead.
func (*ExtensionConfig) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_extension_proto_rawDescGZIP(), []int{2}
}

func (x *ExtensionConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExtensionConfig) GetConfig() [][]byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_tero_policy_v1_extension_proto protoreflect.FileDescriptor

const file_tero_policy_v1_extension_proto_rawDesc = "" +
	"\n" +
	"\x1etero/policy/v1/extension.proto\x12\x0etero.policy.v1\"\x84\x01\n" +
	"\tExtension\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x121\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1d.tero.policy.v1.ExtensionModeR\x04mode\"b\n" +
	"\x13ExtensionCapability\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\tR\n" +
	"minVersion\x12\x16\n" +
	"\x06config\x18\x03 \x03(\fR\x06config\"=\n" +
	"\x0fExtensionConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x02 \x03(\fR\x06config*\xb6\x01\n" +
	"\rExtensionMode\x12\x1e\n" +
	"\x1aEXTENSION_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXTENSION_MODE_KEPT\x10\x01\x12\x1a\n" +
	"\x16EXTENSION_MODE_DROPPED\x10\x02\x12\x1c\n" +
	"\x18EXTENSION_MODE_UNMATCHED\x10\x03\x12\x1a\n" +
	"\x16EXTENSION_MODE_MATCHED\x10\x04\x12\x16\n" +
	"\x12EXTENSION_MODE_ALL\x10\x05B1Z/github.com/usetero/policy/gen/go/tero/policy/v1b\x06proto3"

var (
	file_tero_policy_v1_extension_proto_rawDescOnce sync.Once
	file_tero_policy_v1_extension_proto_rawDescData []byte
)

func file_tero_policy_v1_extension_proto_rawDescGZIP() []byte {
	file_tero_policy_v1_extension_proto_rawDescOnce.Do(func() {
		file_tero_policy_v1_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tero_policy_v1_extension_proto_rawDesc), len(file_tero_policy_v1_extension_proto_rawDesc)))
	})
	return file_tero_policy_v1_extension_proto_rawDescData
}

var file_tero_policy_v1_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tero_policy_v1_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tero_policy_v1_extension_proto_goTypes = []any{
	(ExtensionMode)(0),          // 0: tero.policy.v1.ExtensionMode
	(*Extension)(nil),           // 1: tero.policy.v1.Extension
	(*ExtensionCapability)(nil), // 2: tero.policy.v1.ExtensionCapability
	(*ExtensionConfig)(nil),     // 3: tero.policy.v1.ExtensionConfig
}
var file_tero_policy_v1_extension_proto_depIdxs = []int32{
	0, // 0: tero.policy.v1.Extension.mode:type_name -> tero.policy.v1.ExtensionMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tero_policy_v1_extension_proto_init() }
func file_tero_policy_v1_extension_proto_init() {
	if File_tero_policy_v1_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tero_policy_v1_extension_proto_rawDesc), len(file_tero_policy_v1_extension_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tero_policy_v1_extension_proto_goTypes,
		DependencyIndexes: file_tero_policy_v1_extension_proto_depIdxs,
		EnumInfos:         file_tero_policy_v1_extension_proto_enumTypes,
		MessageInfos:      file_tero_policy_v1_extension_proto_msgTypes,
	}.Build()
	File_tero_policy_v1_extension_proto = out.File
	file_tero_policy_v1_extension_proto_goTypes = nil
	file_tero_policy_v1_extension_proto_depIdxs = nil
}
