// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tero/policy/v1/metric.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricField identifies simple metric fields (non-keyed).
type MetricField int32

const (
	MetricField_METRIC_FIELD_UNSPECIFIED MetricField = 0
	// Metric descriptor fields
	MetricField_METRIC_FIELD_NAME        MetricField = 1
	MetricField_METRIC_FIELD_DESCRIPTION MetricField = 2
	MetricField_METRIC_FIELD_UNIT        MetricField = 3
	// Schema URLs
	MetricField_METRIC_FIELD_RESOURCE_SCHEMA_URL MetricField = 10
	MetricField_METRIC_FIELD_SCOPE_SCHEMA_URL    MetricField = 11
	// Scope fields (InstrumentationScope)
	MetricField_METRIC_FIELD_SCOPE_NAME    MetricField = 12
	MetricField_METRIC_FIELD_SCOPE_VERSION MetricField = 13
)

// Enum value maps for MetricField.
var (
	MetricField_name = map[int32]string{
		0:  "METRIC_FIELD_UNSPECIFIED",
		1:  "METRIC_FIELD_NAME",
		2:  "METRIC_FIELD_DESCRIPTION",
		3:  "METRIC_FIELD_UNIT",
		10: "METRIC_FIELD_RESOURCE_SCHEMA_URL",
		11: "METRIC_FIELD_SCOPE_SCHEMA_URL",
		12: "METRIC_FIELD_SCOPE_NAME",
		13: "METRIC_FIELD_SCOPE_VERSION",
	}
	MetricField_value = map[string]int32{
		"METRIC_FIELD_UNSPECIFIED":         0,
		"METRIC_FIELD_NAME":                1,
		"METRIC_FIELD_DESCRIPTION":         2,
		"METRIC_FIELD_UNIT":                3,
		"METRIC_FIELD_RESOURCE_SCHEMA_URL": 10,
		"METRIC_FIELD_SCOPE_SCHEMA_URL":    11,
		"METRIC_FIELD_SCOPE_NAME":          12,
		"METRIC_FIELD_SCOPE_VERSION":       13,
	}
)

func (x MetricField) Enum() *MetricField {
	p := new(MetricField)
	*p = x
	return p
}

func (x MetricField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricField) Descriptor() protoreflect.EnumDescriptor {
	return file_tero_policy_v1_metric_proto_enumTypes[0].Descriptor()
}

func (MetricField) Type() protoreflect.EnumType {
	return &file_tero_policy_v1_metric_proto_enumTypes[0]
}

func (x MetricField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricField.Descriptor instead.
func (MetricField) EnumDescriptor() ([]byte, []int) {
	return file_tero_policy_v1_metric_proto_rawDescGZIP(), []int{0}
}

// MetricType identifies the type of metric for matching.
type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED           MetricType = 0
	MetricType_METRIC_TYPE_GAUGE                 MetricType = 1
	MetricType_METRIC_TYPE_SUM                   MetricType = 2
	MetricType_METRIC_TYPE_HISTOGRAM             MetricType = 3
	MetricType_METRIC_TYPE_EXPONENTIAL_HISTOGRAM MetricType = 4
	MetricType_METRIC_TYPE_SUMMARY               MetricType = 5
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_GAUGE",
		2: "METRIC_TYPE_SUM",
		3: "METRIC_TYPE_HISTOGRAM",
		4: "METRIC_TYPE_EXPONENTIAL_HISTOGRAM",
		5: "METRIC_TYPE_SUMMARY",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED":           0,
		"METRIC_TYPE_GAUGE":                 1,
		"METRIC_TYPE_SUM":                   2,
		"METRIC_TYPE_HISTOGRAM":             3,
		"METRIC_TYPE_EXPONENTIAL_HISTOGRAM": 4,
		"METRIC_TYPE_SUMMARY":               5,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_tero_policy_v1_metric_proto_enumTypes[1].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_tero_policy_v1_metric_proto_enumTypes[1]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_tero_policy_v1_metric_proto_rawDescGZIP(), []int{1}
}

// AggregationTemporality defines how a metric aggregator reports aggregated values.
// Mirrors opentelemetry.proto.metrics.v1.AggregationTemporality.
type AggregationTemporality int32

const (
	AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED AggregationTemporality = 0
	AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA       AggregationTemporality = 1
	AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE  AggregationTemporality = 2
)

// Enum value maps for AggregationTemporality.
var (
	AggregationTemporality_name = map[int32]string{
		0: "AGGREGATION_TEMPORALITY_UNSPECIFIED",
		1: "AGGREGATION_TEMPORALITY_DELTA",
		2: "AGGREGATION_TEMPORALITY_CUMULATIVE",
	}
	AggregationTemporality_value = map[string]int32{
		"AGGREGATION_TEMPORALITY_UNSPECIFIED": 0,
		"AGGREGATION_TEMPORALITY_DELTA":       1,
		"AGGREGATION_TEMPORALITY_CUMULATIVE":  2,
	}
)

func (x AggregationTemporality) Enum() *AggregationTemporality {
	p := new(AggregationTemporality)
	*p = x
	return p
}

func (x AggregationTemporality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationTemporality) Descriptor() protoreflect.EnumDescriptor {
	return file_tero_policy_v1_metric_proto_enumTypes[2].Descriptor()
}

func (AggregationTemporality) Type() protoreflect.EnumType {
	return &file_tero_policy_v1_metric_proto_enumTypes[2]
}

func (x AggregationTemporality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationTemporality.Descriptor instead.
func (AggregationTemporality) EnumDescriptor() ([]byte, []int) {
	return file_tero_policy_v1_metric_proto_rawDescGZIP(), []int{2}
}

// MetricTarget defines matching and actions for metrics.
type MetricTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matchers to identify which metrics this policy applies to (AND logic)
	Match []*MetricMatcher `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	// Whether to keep matching metrics (true) or drop them (false)
	Keep          bool `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricTarget) Reset() {
	*x = MetricTarget{}
	mi := &file_tero_policy_v1_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricTarget) ProtoMessage() {}

func (x *MetricTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricTarget.ProtoReflect.Descriptor instead.
func (*MetricTarget) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_metric_proto_rawDescGZIP(), []int{0}
}

func (x *MetricTarget) GetMatch() []*MetricMatcher {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *MetricTarget) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

// MetricMatcher provides a way to match against metric telemetry data using known fields.
//
// IMPORTANT CONSTRAINTS:
//   - Multiple matchers are ANDed together: all matchers must match for the
//     overall match to succeed.
//   - The list of matchers should uniquely identify a specific pattern of telemetry
//     for that policy. Matchers should NOT be used as a catch-all; they should be
//     specific enough to target the intended telemetry precisely.
//
// All regex fields use RE2 syntax for consistency across implementations.
type MetricMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FIELD SELECTION
	// The field to match against. Exactly one must be set.
	//
	// Types that are valid to be assigned to Field:
	//
	//	*MetricMatcher_MetricField
	//	*MetricMatcher_DatapointAttribute
	//	*MetricMatcher_ResourceAttribute
	//	*MetricMatcher_ScopeAttribute
	//	*MetricMatcher_MetricType
	//	*MetricMatcher_AggregationTemporality
	Field isMetricMatcher_Field `protobuf_oneof:"field"`
	// Match type. Exactly one must be set.
	// Note: For metric_type field, only exists is valid (type equality is implicit).
	//
	// Types that are valid to be assigned to Match:
	//
	//	*MetricMatcher_Exact
	//	*MetricMatcher_Regex
	//	*MetricMatcher_Exists
	//	*MetricMatcher_StartsWith
	//	*MetricMatcher_EndsWith
	//	*MetricMatcher_Contains
	Match isMetricMatcher_Match `protobuf_oneof:"match"`
	// If true, inverts the match result
	Negate bool `protobuf:"varint,20,opt,name=negate,proto3" json:"negate,omitempty"`
	// If true, applies case-insensitive matching to all match types
	CaseInsensitive bool `protobuf:"varint,21,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricMatcher) Reset() {
	*x = MetricMatcher{}
	mi := &file_tero_policy_v1_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricMatcher) ProtoMessage() {}

func (x *MetricMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricMatcher.ProtoReflect.Descriptor instead.
func (*MetricMatcher) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_metric_proto_rawDescGZIP(), []int{1}
}

func (x *MetricMatcher) GetField() isMetricMatcher_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *MetricMatcher) GetMetricField() MetricField {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_MetricField); ok {
			return x.MetricField
		}
	}
	return MetricField_METRIC_FIELD_UNSPECIFIED
}

func (x *MetricMatcher) GetDatapointAttribute() *AttributePath {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_DatapointAttribute); ok {
			return x.DatapointAttribute
		}
	}
	return nil
}

func (x *MetricMatcher) GetResourceAttribute() *AttributePath {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_ResourceAttribute); ok {
			return x.ResourceAttribute
		}
	}
	return nil
}

func (x *MetricMatcher) GetScopeAttribute() *AttributePath {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_ScopeAttribute); ok {
			return x.ScopeAttribute
		}
	}
	return nil
}

func (x *MetricMatcher) GetMetricType() MetricType {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_MetricType); ok {
			return x.MetricType
		}
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *MetricMatcher) GetAggregationTemporality() AggregationTemporality {
	if x != nil {
		if x, ok := x.Field.(*MetricMatcher_AggregationTemporality); ok {
			return x.AggregationTemporality
		}
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

func (x *MetricMatcher) GetMatch() isMetricMatcher_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *MetricMatcher) GetExact() string {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_Exact); ok {
			return x.Exact
		}
	}
	return ""
}

func (x *MetricMatcher) GetRegex() string {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_Regex); ok {
			return x.Regex
		}
	}
	return ""
}

func (x *MetricMatcher) GetExists() bool {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_Exists); ok {
			return x.Exists
		}
	}
	return false
}

func (x *MetricMatcher) GetStartsWith() string {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_StartsWith); ok {
			return x.StartsWith
		}
	}
	return ""
}

func (x *MetricMatcher) GetEndsWith() string {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_EndsWith); ok {
			return x.EndsWith
		}
	}
	return ""
}

func (x *MetricMatcher) GetContains() string {
	if x != nil {
		if x, ok := x.Match.(*MetricMatcher_Contains); ok {
			return x.Contains
		}
	}
	return ""
}

func (x *MetricMatcher) GetNegate() bool {
	if x != nil {
		return x.Negate
	}
	return false
}

func (x *MetricMatcher) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

type isMetricMatcher_Field interface {
	isMetricMatcher_Field()
}

type MetricMatcher_MetricField struct {
	// Simple fields (name, description, unit, etc.)
	MetricField MetricField `protobuf:"varint,1,opt,name=metric_field,json=metricField,proto3,enum=tero.policy.v1.MetricField,oneof"`
}

type MetricMatcher_DatapointAttribute struct {
	// Data point attribute by key or path
	DatapointAttribute *AttributePath `protobuf:"bytes,2,opt,name=datapoint_attribute,json=datapointAttribute,proto3,oneof"`
}

type MetricMatcher_ResourceAttribute struct {
	// Resource attribute by key or path
	ResourceAttribute *AttributePath `protobuf:"bytes,3,opt,name=resource_attribute,json=resourceAttribute,proto3,oneof"`
}

type MetricMatcher_ScopeAttribute struct {
	// Scope attribute by key or path
	ScopeAttribute *AttributePath `protobuf:"bytes,4,opt,name=scope_attribute,json=scopeAttribute,proto3,oneof"`
}

type MetricMatcher_MetricType struct {
	// Metric type matcher
	MetricType MetricType `protobuf:"varint,5,opt,name=metric_type,json=metricType,proto3,enum=tero.policy.v1.MetricType,oneof"`
}

type MetricMatcher_AggregationTemporality struct {
	// Aggregation temporality matcher (applies to Sum, Histogram, ExponentialHistogram)
	AggregationTemporality AggregationTemporality `protobuf:"varint,6,opt,name=aggregation_temporality,json=aggregationTemporality,proto3,enum=tero.policy.v1.AggregationTemporality,oneof"`
}

func (*MetricMatcher_MetricField) isMetricMatcher_Field() {}

func (*MetricMatcher_DatapointAttribute) isMetricMatcher_Field() {}

func (*MetricMatcher_ResourceAttribute) isMetricMatcher_Field() {}

func (*MetricMatcher_ScopeAttribute) isMetricMatcher_Field() {}

func (*MetricMatcher_MetricType) isMetricMatcher_Field() {}

func (*MetricMatcher_AggregationTemporality) isMetricMatcher_Field() {}

type isMetricMatcher_Match interface {
	isMetricMatcher_Match()
}

type MetricMatcher_Exact struct {
	// Exact string match
	Exact string `protobuf:"bytes,10,opt,name=exact,proto3,oneof"`
}

type MetricMatcher_Regex struct {
	// Regular expression match
	Regex string `protobuf:"bytes,11,opt,name=regex,proto3,oneof"`
}

type MetricMatcher_Exists struct {
	// Field existence check
	Exists bool `protobuf:"varint,12,opt,name=exists,proto3,oneof"`
}

type MetricMatcher_StartsWith struct {
	// Literal prefix match
	StartsWith string `protobuf:"bytes,13,opt,name=starts_with,json=startsWith,proto3,oneof"`
}

type MetricMatcher_EndsWith struct {
	// Literal suffix match
	EndsWith string `protobuf:"bytes,14,opt,name=ends_with,json=endsWith,proto3,oneof"`
}

type MetricMatcher_Contains struct {
	// Literal substring match
	Contains string `protobuf:"bytes,15,opt,name=contains,proto3,oneof"`
}

func (*MetricMatcher_Exact) isMetricMatcher_Match() {}

func (*MetricMatcher_Regex) isMetricMatcher_Match() {}

func (*MetricMatcher_Exists) isMetricMatcher_Match() {}

func (*MetricMatcher_StartsWith) isMetricMatcher_Match() {}

func (*MetricMatcher_EndsWith) isMetricMatcher_Match() {}

func (*MetricMatcher_Contains) isMetricMatcher_Match() {}

var File_tero_policy_v1_metric_proto protoreflect.FileDescriptor

const file_tero_policy_v1_metric_proto_rawDesc = "" +
	"\n" +
	"\x1btero/policy/v1/metric.proto\x12\x0etero.policy.v1\x1a\x1btero/policy/v1/shared.proto\"W\n" +
	"\fMetricTarget\x123\n" +
	"\x05match\x18\x01 \x03(\v2\x1d.tero.policy.v1.MetricMatcherR\x05match\x12\x12\n" +
	"\x04keep\x18\x02 \x01(\bR\x04keep\"\xde\x05\n" +
	"\rMetricMatcher\x12@\n" +
	"\fmetric_field\x18\x01 \x01(\x0e2\x1b.tero.policy.v1.MetricFieldH\x00R\vmetricField\x12P\n" +
	"\x13datapoint_attribute\x18\x02 \x01(\v2\x1d.tero.policy.v1.AttributePathH\x00R\x12datapointAttribute\x12N\n" +
	"\x12resource_attribute\x18\x03 \x01(\v2\x1d.tero.policy.v1.AttributePathH\x00R\x11resourceAttribute\x12H\n" +
	"\x0fscope_attribute\x18\x04 \x01(\v2\x1d.tero.policy.v1.AttributePathH\x00R\x0escopeAttribute\x12=\n" +
	"\vmetric_type\x18\x05 \x01(\x0e2\x1a.tero.policy.v1.MetricTypeH\x00R\n" +
	"metricType\x12a\n" +
	"\x17aggregation_temporality\x18\x06 \x01(\x0e2&.tero.policy.v1.AggregationTemporalityH\x00R\x16aggregationTemporality\x12\x16\n" +
	"\x05exact\x18\n" +
	" \x01(\tH\x01R\x05exact\x12\x16\n" +
	"\x05regex\x18\v \x01(\tH\x01R\x05regex\x12\x18\n" +
	"\x06exists\x18\f \x01(\bH\x01R\x06exists\x12!\n" +
	"\vstarts_with\x18\r \x01(\tH\x01R\n" +
	"startsWith\x12\x1d\n" +
	"\tends_with\x18\x0e \x01(\tH\x01R\bendsWith\x12\x1c\n" +
	"\bcontains\x18\x0f \x01(\tH\x01R\bcontains\x12\x16\n" +
	"\x06negate\x18\x14 \x01(\bR\x06negate\x12)\n" +
	"\x10case_insensitive\x18\x15 \x01(\bR\x0fcaseInsensitiveB\a\n" +
	"\x05fieldB\a\n" +
	"\x05match*\xfd\x01\n" +
	"\vMetricField\x12\x1c\n" +
	"\x18METRIC_FIELD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11METRIC_FIELD_NAME\x10\x01\x12\x1c\n" +
	"\x18METRIC_FIELD_DESCRIPTION\x10\x02\x12\x15\n" +
	"\x11METRIC_FIELD_UNIT\x10\x03\x12$\n" +
	" METRIC_FIELD_RESOURCE_SCHEMA_URL\x10\n" +
	"\x12!\n" +
	"\x1dMETRIC_FIELD_SCOPE_SCHEMA_URL\x10\v\x12\x1b\n" +
	"\x17METRIC_FIELD_SCOPE_NAME\x10\f\x12\x1e\n" +
	"\x1aMETRIC_FIELD_SCOPE_VERSION\x10\r*\xb0\x01\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11METRIC_TYPE_GAUGE\x10\x01\x12\x13\n" +
	"\x0fMETRIC_TYPE_SUM\x10\x02\x12\x19\n" +
	"\x15METRIC_TYPE_HISTOGRAM\x10\x03\x12%\n" +
	"!METRIC_TYPE_EXPONENTIAL_HISTOGRAM\x10\x04\x12\x17\n" +
	"\x13METRIC_TYPE_SUMMARY\x10\x05*\x8c\x01\n" +
	"\x16AggregationTemporality\x12'\n" +
	"#AGGREGATION_TEMPORALITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGGREGATION_TEMPORALITY_DELTA\x10\x01\x12&\n" +
	"\"AGGREGATION_TEMPORALITY_CUMULATIVE\x10\x02B1Z/github.com/usetero/policy/gen/go/tero/policy/v1b\x06proto3"

var (
	file_tero_policy_v1_metric_proto_rawDescOnce sync.Once
	file_tero_policy_v1_metric_proto_rawDescData []byte
)

func file_tero_policy_v1_metric_proto_rawDescGZIP() []byte {
	file_tero_policy_v1_metric_proto_rawDescOnce.Do(func() {
		file_tero_policy_v1_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tero_policy_v1_metric_proto_rawDesc), len(file_tero_policy_v1_metric_proto_rawDesc)))
	})
	return file_tero_policy_v1_metric_proto_rawDescData
}

var file_tero_policy_v1_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tero_policy_v1_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tero_policy_v1_metric_proto_goTypes = []any{
	(MetricField)(0),            // 0: tero.policy.v1.MetricField
	(MetricType)(0),             // 1: tero.policy.v1.MetricType
	(AggregationTemporality)(0), // 2: tero.policy.v1.AggregationTemporality
	(*MetricTarget)(nil),        // 3: tero.policy.v1.MetricTarget
	(*MetricMatcher)(nil),       // 4: tero.policy.v1.MetricMatcher
	(*AttributePath)(nil),       // 5: tero.policy.v1.AttributePath
}
var file_tero_policy_v1_metric_proto_depIdxs = []int32{
	4, // 0: tero.policy.v1.MetricTarget.match:type_name -> tero.policy.v1.MetricMatcher
	0, // 1: tero.policy.v1.MetricMatcher.metric_field:type_name -> tero.policy.v1.MetricField
	5, // 2: tero.policy.v1.MetricMatcher.datapoint_attribute:type_name -> tero.policy.v1.AttributePath
	5, // 3: tero.policy.v1.MetricMatcher.resource_attribute:type_name -> tero.policy.v1.AttributePath
	5, // 4: tero.policy.v1.MetricMatcher.scope_attribute:type_name -> tero.policy.v1.AttributePath
	1, // 5: tero.policy.v1.MetricMatcher.metric_type:type_name -> tero.policy.v1.MetricType
	2, // 6: tero.policy.v1.MetricMatcher.aggregation_temporality:type_name -> tero.policy.v1.AggregationTemporality
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tero_policy_v1_metric_proto_init() }
func file_tero_policy_v1_metric_proto_init() {
	if File_tero_policy_v1_metric_proto != nil {
		return
	}
	file_tero_policy_v1_shared_proto_init()
	file_tero_policy_v1_metric_proto_msgTypes[1].OneofWrappers = []any{
		(*MetricMatcher_MetricField)(nil),
		(*MetricMatcher_DatapointAttribute)(nil),
		(*MetricMatcher_ResourceAttribute)(nil),
		(*MetricMatcher_ScopeAttribute)(nil),
		(*MetricMatcher_MetricType)(nil),
		(*MetricMatcher_AggregationTemporality)(nil),
		(*MetricMatcher_Exact)(nil),
		(*MetricMatcher_Regex)(nil),
		(*MetricMatcher_Exists)(nil),
		(*MetricMatcher_StartsWith)(nil),
		(*MetricMatcher_EndsWith)(nil),
		(*MetricMatcher_Contains)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tero_policy_v1_metric_proto_rawDesc), len(file_tero_policy_v1_metric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tero_policy_v1_metric_proto_goTypes,
		DependencyIndexes: file_tero_policy_v1_metric_proto_depIdxs,
		EnumInfos:         file_tero_policy_v1_metric_proto_enumTypes,
		MessageInfos:      file_tero_policy_v1_metric_proto_msgTypes,
	}.Build()
	File_tero_policy_v1_metric_proto = out.File
	file_tero_policy_v1_metric_proto_goTypes = nil
	file_tero_policy_v1_metric_proto_depIdxs = nil
}
