// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tero/policy/v1/shared.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributePath specifies how to access an attribute value.
//
// The path is represented as an array of string segments. Each segment represents
// a key to traverse into nested maps.
//
// Example usage:
//
//	For an attribute structure like:
//	  Attributes: map[string]any{
//	      "http": map[string]any{
//	          "method":      "POST",
//	          "status_code": 200,
//	      },
//	      "user_id": "u123",
//	  }
//
//	- To access "user_id": ["user_id"]
//	- To access http.method: ["http", "method"]
//
// YAML/JSON Unmarshaling:
//
// Implementations MUST accept both the canonical proto form and shorthand forms
// for ergonomic policy authoring:
//
//	Canonical (proto-native):
//	  log_attribute:
//	    path: ["http", "method"]
//
//	Shorthand array (MUST be supported):
//	  log_attribute: ["http", "method"]
//
//	Shorthand string (MUST be supported for single-segment paths):
//	  log_attribute: "user_id"           # equivalent to ["user_id"]
//
// When marshaling, implementations SHOULD use the shorthand array form for
// cleaner output.
type AttributePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path segments for attribute traversal.
	// A single-element array accesses a flat attribute.
	// Multiple elements traverse nested maps.
	Path          []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributePath) Reset() {
	*x = AttributePath{}
	mi := &file_tero_policy_v1_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributePath) ProtoMessage() {}

func (x *AttributePath) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributePath.ProtoReflect.Descriptor instead.
func (*AttributePath) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_shared_proto_rawDescGZIP(), []int{0}
}

func (x *AttributePath) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_tero_policy_v1_shared_proto protoreflect.FileDescriptor

const file_tero_policy_v1_shared_proto_rawDesc = "" +
	"\n" +
	"\x1btero/policy/v1/shared.proto\x12\x0etero.policy.v1\"#\n" +
	"\rAttributePath\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04pathB1Z/github.com/usetero/policy/gen/go/tero/policy/v1b\x06proto3"

var (
	file_tero_policy_v1_shared_proto_rawDescOnce sync.Once
	file_tero_policy_v1_shared_proto_rawDescData []byte
)

func file_tero_policy_v1_shared_proto_rawDescGZIP() []byte {
	file_tero_policy_v1_shared_proto_rawDescOnce.Do(func() {
		file_tero_policy_v1_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tero_policy_v1_shared_proto_rawDesc), len(file_tero_policy_v1_shared_proto_rawDesc)))
	})
	return file_tero_policy_v1_shared_proto_rawDescData
}

var file_tero_policy_v1_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tero_policy_v1_shared_proto_goTypes = []any{
	(*AttributePath)(nil), // 0: tero.policy.v1.AttributePath
}
var file_tero_policy_v1_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tero_policy_v1_shared_proto_init() }
func file_tero_policy_v1_shared_proto_init() {
	if File_tero_policy_v1_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tero_policy_v1_shared_proto_rawDesc), len(file_tero_policy_v1_shared_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tero_policy_v1_shared_proto_goTypes,
		DependencyIndexes: file_tero_policy_v1_shared_proto_depIdxs,
		MessageInfos:      file_tero_policy_v1_shared_proto_msgTypes,
	}.Build()
	File_tero_policy_v1_shared_proto = out.File
	file_tero_policy_v1_shared_proto_goTypes = nil
	file_tero_policy_v1_shared_proto_depIdxs = nil
}
