// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tero/policy/v1/tero_extensions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExtensionTarget is a pre-configured, named destination an extension can route
// telemetry to (for example, an S3 bucket or a downstream OTLP endpoint).
//
// Targets are configured out of band on the implementation, or broadcast to
// clients via SyncResponse.extension_configs (serialized into the s3-dump
// extension's config). Policies reference a target by (kind, name) via
// ExtensionTargetRef and never carry its configuration inline.
type ExtensionTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination kind, e.g. "s3" or "otlp".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name, unique within a kind, e.g. "eu-bucket". Used as the reference key.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque, kind-defined configuration (e.g. region, bucket, prefix).
	Config        []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionTarget) Reset() {
	*x = ExtensionTarget{}
	mi := &file_tero_policy_v1_tero_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionTarget) ProtoMessage() {}

func (x *ExtensionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_tero_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionTarget.ProtoReflect.Descriptor instead.
func (*ExtensionTarget) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_tero_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *ExtensionTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExtensionTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionTarget) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

// ExtensionTargetRef references a pre-configured ExtensionTarget by identity.
// Carried inside an Extension's config (to name where it routes) and inside an
// ExtensionCapability's config (to advertise reachable destinations). The
// referenced target MUST be known to the implementation — locally configured or
// received via SyncResponse.extension_configs.
type ExtensionTargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionTargetRef) Reset() {
	*x = ExtensionTargetRef{}
	mi := &file_tero_policy_v1_tero_extensions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionTargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionTargetRef) ProtoMessage() {}

func (x *ExtensionTargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_tero_policy_v1_tero_extensions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionTargetRef.ProtoReflect.Descriptor instead.
func (*ExtensionTargetRef) Descriptor() ([]byte, []int) {
	return file_tero_policy_v1_tero_extensions_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionTargetRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExtensionTargetRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_tero_policy_v1_tero_extensions_proto protoreflect.FileDescriptor

const file_tero_policy_v1_tero_extensions_proto_rawDesc = "" +
	"\n" +
	"$tero/policy/v1/tero_extensions.proto\x12\x0etero.policy.v1\"Q\n" +
	"\x0fExtensionTarget\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\"<\n" +
	"\x12ExtensionTargetRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB1Z/github.com/usetero/policy/gen/go/tero/policy/v1b\x06proto3"

var (
	file_tero_policy_v1_tero_extensions_proto_rawDescOnce sync.Once
	file_tero_policy_v1_tero_extensions_proto_rawDescData []byte
)

func file_tero_policy_v1_tero_extensions_proto_rawDescGZIP() []byte {
	file_tero_policy_v1_tero_extensions_proto_rawDescOnce.Do(func() {
		file_tero_policy_v1_tero_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tero_policy_v1_tero_extensions_proto_rawDesc), len(file_tero_policy_v1_tero_extensions_proto_rawDesc)))
	})
	return file_tero_policy_v1_tero_extensions_proto_rawDescData
}

var file_tero_policy_v1_tero_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tero_policy_v1_tero_extensions_proto_goTypes = []any{
	(*ExtensionTarget)(nil),    // 0: tero.policy.v1.ExtensionTarget
	(*ExtensionTargetRef)(nil), // 1: tero.policy.v1.ExtensionTargetRef
}
var file_tero_policy_v1_tero_extensions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tero_policy_v1_tero_extensions_proto_init() }
func file_tero_policy_v1_tero_extensions_proto_init() {
	if File_tero_policy_v1_tero_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tero_policy_v1_tero_extensions_proto_rawDesc), len(file_tero_policy_v1_tero_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tero_policy_v1_tero_extensions_proto_goTypes,
		DependencyIndexes: file_tero_policy_v1_tero_extensions_proto_depIdxs,
		MessageInfos:      file_tero_policy_v1_tero_extensions_proto_msgTypes,
	}.Build()
	File_tero_policy_v1_tero_extensions_proto = out.File
	file_tero_policy_v1_tero_extensions_proto_goTypes = nil
	file_tero_policy_v1_tero_extensions_proto_depIdxs = nil
}
